---
- name: Adding a 'gogs' user
  user:
    name: gogs
    shell: /usr/sbin/nologin

- apt_repository:
    repo: ppa:longsleep/golang-backports

- name: Installing packages
  apt:
    name: "{{ item }}"
    force_apt_get: true
  loop: "{{ packages_2_be_installed }}"

- name: Create Go's sources directory
  file:
    path: "{{ gopath }}"
    state: directory
    owner: gogs

- name: Getting Gogs & ska.
  git:
    repo: https://github.com/gogs/gogs.git
    dest: "{{ gopath }}/gogs"
    version: master
    update: no
  become_user: gogs
  become: yes
  environment:
    GOPATH: "{{ gopath }}"

- name: Install Gogs
  shell: # noqa 305
    cmd: go build -o gogs
    chdir: "{{ gopath }}/gogs"
    creates: "{{ gopath }}/gogs/gogs"
  become_user: gogs
  become: yes
  environment:
    GOPATH: "{{ gopath }}"

- name: Start service PostgreSQL
  service:
    name: postgresql
    state: started
    enabled: true

- name: Create a new database with name gogs
  postgresql_db:
    name: "{{ postgres_db }}"
  become: yes
  become_user: postgres

- name: Connect to gogs database, create user gogs and grant access to the database
  postgresql_user:
    db: "{{ postgres_db }}"
    name: "{{ postgres_db_user }}"
    password: "{{ postgres_db_password }}"
  become: yes
  become_user: postgres

- name: Ensures {{ gopath }}/custom/conf/ dir exists
  file:
    path: "{{ gopath }}/custom/conf/"
    state: directory

- name: Copy a new app.ini file into place
  template:
    src: app.ini.j2
    dest: "{{ gopath }}/custom/conf/app.ini"
    backup: yes
  notify: gogs_restart

- name: Install gogs as a service
  template:
    src: gogs.service.j2
    dest: "/etc/systemd/system/gogs.service"
    backup: yes
  notify: gogs_restart
