---
- name: Adding a 'gogs' user
  user:
    name: gogs
    shell: /usr/sbin/nologin

- name: Installing packages
  apt:
    name: "{{ item }}"
    force_apt_get: true
  loop: "{{ packages_2_be_installed }}"

- name: Create Go's sources directory
  file:
    path: "{{ gopath }}"
    state: directory
    owner: gogs

- name: Getting Gogs & ska.
  shell: |
    go get -u github.com/gogs/gogs
    cd ${GOPATH}/src/github.com/gogs/gogs
    go build github.com/gogs/gogs
  args:
    creates: "{{ gopath }}/src/github.com/gogs/gogs/gogs"
  become_user: gogs
  environment:
    GOPATH: "{{ gopath }}"

- name: Start service PostgreSQL
  service:
    name: postgresql
    state: started
    enabled: true

- name: Create a new database with name gogs
  postgresql_db:
    name: gogs
  become: yes
  become_user: postgres

- name: Connect to gogs database, create user gogs and grant access to the database
  postgresql_user:
    db: gogs
    name: gogs
    password: gogs
  become: yes
  become_user: postgres
