---
- name: Converge
  hosts: all
  gather_facts: no
  tasks:
    - name: Install gnupg & software-properties-common
      apt:
        name: [software-properties-common, gnupg2]
        update_cache: true

    - name: Run gogs role
      include_role:
        name: gogs
